/**
 * 
 */
package org.frameworkset.platform.common;

import java.util.Map;

/**
 * 封装树节点对象
 * @author yinbp { id : "string" // will be autogenerated if omitted text :
 *         "string" // node text icon : "string" // string for custom state : {
 *         opened : boolean // is the node open disabled : boolean // is the
 *         node disabled selected : boolean // is the node selected }, children
 *         : [] // array of strings or objects li_attr : {} // attributes for
 *         the generated LI node a_attr : {} // attributes for the generated A
 *         node }
 * @Date:2016-11-28 18:14:38
 */
public class ZKTreeNode {

	private String id;// will be autogenerated if omitted
	private String name;// node text
	private boolean isParent;
	/**
	 * 
	 */
	public ZKTreeNode() {
		// TODO Auto-generated constructor stub
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isIsParent() {
		return isParent;
	}
	public void setIsParent(boolean isParent) {
		this.isParent = isParent;
	}


}
