<!-- bootstrap基础框架样式 -->
<link href="${pageContext.request.contextPath}/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<!-- 字体图标样式 -->
<link href="${pageContext.request.contextPath}/static/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<!-- css动画样式 -->
<link href="${pageContext.request.contextPath}/static/css/animate.min.css" rel="stylesheet" type="text/css">
<!-- 下拉框样式 -->
<link href="${pageContext.request.contextPath}/static/css/plugins/chosen/chosen.css" rel="stylesheet" type="text/css">
<!-- zTree样式 -->
<link href="${pageContext.request.contextPath}/static/css/plugins/zTree/metroStyle.css" rel="stylesheet" type="text/css">
<!-- 自定义样式 -->
<link href="${pageContext.request.contextPath}/static/css/style.css" rel="stylesheet" type="text/css">
<link href="${pageContext.request.contextPath}/static/plugins/bootstrap-toastr/toastr.min.css" rel="stylesheet" type="text/css" />