<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/jquery.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/contabs.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>

<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/jquery-validation/jquery.validate.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/jquery-validation/additional-methods.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/static/plugins/bootstrap-toastr/toastr.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath}/static/plugins/jquery.form.js" type="text/javascript"></script>

<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/plugins/layer301/layer.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/plugins/pace/pace.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/plugins/chosen/chosen.jquery.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/plugins/zTree/jquery.ztree.all.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/datagrid.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/js/sdp.js"></script>

